version: '2'
services:
  coinrank:
    build: .
    container_name: coinrank-appcp
    ports:
      - "8080:8080"
      - "4848:4848"
    networks:
      coinrank_net:
        ipv4_address: 172.28.0.10

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      coinrank_net:
        ipv4_address: 172.28.0.2

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.28.0.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logs:1:1,users:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      coinrank_net:
        ipv4_address: 172.28.0.3

  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: coin_rank
      MYSQL_USER: coin_user
      MYSQL_DATABASE: coinrank
    volumes:
      - c:\tmp\coinrank:/var/lib/mysql
    networks:
      coinrank_net:
        ipv4_address: 172.28.0.100

networks:
  coinrank_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24